### ISSUE TITLE
Running on Digital Ocean

### ISSUE THREAD

**Issue by tororutsu** [mufeedvh/gisture#2]
I need to learn how to use this! I have a very cool idea that I believe this will help me with!
I now just need to understand some basics. How do I get this on the web?
I have a DigitalOcean Droplet with Gesture on it. I edit the `github_username & blog_url` to what I need.
I point my DNS to the DO droplet and nothing. Can you please help me with this lol

**Comment by mufeedvh** [comment]
Sure man! You can configure NGINX to reverse proxy the serving port from gisture or place the generated static files directly from NGINX as well. And for DNS, first setup the nameservers (from the domain registrar) and then add the A/CNAME records for the domain from the DigitalOcean network tab.

If you are trying to access gisture directly from the serve feature, it won't be accessible publicly since it runs on `127.0.0.1` and not `0.0.0.0`.

I personally use DigitalOcean as well so If you wanna know more, feel free to DM me on [Twitter](https://twitter.com/mufeedvh). 🙌

**Comment by tororutsu** [comment]
> If you are trying to access gisture directly from the serve feature, it won't be accessible publicly since it runs on `127.0.0.1` and not `0.0.0.0`.

Wow u caught me red-handed lol

> You can configure NGINX to reverse proxy the serving port

This is what I will need help with

> feel free to DM me on [Twitter](https://twitter.com/mufeedvh).

I reached out under the same username

**Comment by tororutsu** [comment]
Thanks for helping solve the issue!
